POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name" : "Faith",
    "email" : "faith@gmail.com",
    "password" : "faith"
}

###

POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
    "email" : "faith@gmail.com",
    "password" : "faith"
}

###


GET http://localhost:5000/api/auth/refresh_token
